# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/TheMatheusDev/android_kernel_xiaomi_sm6225-2
          kernel-dir: spes
          kernel-branch: uvite
          config: vendor/spes-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          android-version: 14
          aosp-clang-version: r487747c
          python-27: true
          disable-lto: false
          anykernel3: true
          anykernel3-url: https://github.com/binhvo7794/AnyKernel3
